### ISSUE TITLE
java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by hed516** [PluginBugs/Issues-CosmeticsCore#266] opened 2024-10-14 15:54 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

[23:49:52 WARN]: [CosmeticsCore] Task #69965699 for CosmeticsCore v1.3.0-release-2 generated an exception
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableList.remove(ImmutableCollections.java:260) ~[?:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.nms.aH.impl.v1_21_1.b(SourceFile:199) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.b(SourceFile:165) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.bm(SourceFile:145) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.q(SourceFile:93) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.c(SourceFile:103) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.j.a(SourceFile:467) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.H.a(SourceFile:402) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.H.a(SourceFile:489) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.aH.run(SourceFile:131) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[23:49:52 WARN]: [CosmeticsCore] Task #69966505 for CosmeticsCore v1.3.0-release-2 generated an exception
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableList.remove(ImmutableCollections.java:260) ~[?:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.nms.aH.impl.v1_21_1.b(SourceFile:199) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.b(SourceFile:165) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.bm(SourceFile:145) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.q(SourceFile:93) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.c(SourceFile:103) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.y.aY(SourceFile:69) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2.jar/dev.lone.cosmeticscore.main.i.ai(SourceFile:560) ~[[ia时装]CosmeticsCore_1.3.0-release-2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-120-57c75a4]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

### Steps to reproduce the issue

hi

### CosmeticsCore Version

new

### ProtocolLib Version

new

### LoneLibs Version

new

**Comment by LoneDev6** [comment] 2024-11-20 16:14
Duplicate of #262

**Closed by LoneDev6** 2024-11-20 16:14 UTC
Labels: type: bug
