### ISSUE TITLE
can't leave wardobe zone

### ISSUE THREAD

**Issue by Ecilpse** [PluginBugs/Issues-CosmeticsCore#226] opened 2024-05-20 12:52 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Eclipse

### What happened?

player can't leave wardobe zone.

### Steps to reproduce the issue

just leave wardrobe zone. 
this problems happend after update protocollib, cosmeticscore 

### Server version

purpur 1.20.1

### CosmeticsCore Version

1.2.3d

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Screenshots/Videos (you can drag and drop files or paste links)

https://github.com/PluginBugs/Issues-CosmeticsCore/assets/25452835/4b510077-bbe6-4a43-a818-bfe3f6cd402d

**Comment by LoneDev6** [comment] 2024-06-06 13:38
Duplicate of #207 

https://github.com/PluginBugs/Issues-CosmeticsCore/issues/207#issuecomment-1969172770

> It's a bug of ProtocolLib `5.2.0-SNAPSHOT-679` and 1.20.2.
> For some reason `PacketType.Play.Client.STEER_VEHICLE.getPacketClass()` returns `ServerboundPongPacket` instead of `PacketPlayInSteerVehicle`.
> I opened a new report here: https://github.com/dmulloy2/ProtocolLib/issues/2818
>

**Closed by LoneDev6** 2024-06-06 13:38 UTC
Labels: type: bug
