### ISSUE TITLE
Backpack disappears after world teleportation

### ISSUE THREAD

**Issue by tyhppp233** [PluginBugs/Issues-CosmeticsCore#135] opened 2023-05-21 16:46 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

tyhppp#6655

### What happened?

The backpack will disappear when the player teleports to a different world after exiting the wardrobe. The balloons and hats are all fine.

### Steps to reproduce the issue

1. Go to wardrobe, wear a backpack
2. Then teleport to a different world, backpack disappears
3. teleport back to the spawn world, where the exit location was set up, the backpack re-appears.

### Server version

This server is running Purpur version git-purpur-1171 (MC:1.16.5) (Implementing API version 1.16.5-R.0.1-SNAPSHOT)

### CosmeticsCore Version

1.2.2c

### ProtocolLib Version

5.1.0-SNAPSHOT-645

### LoneLibs Version

1.0.24

**Comment by LoneDev6** [comment] 2023-06-06 10:41
## 1.16.2
Both server and client are 1.16.2.
I confirm the bug is reproducible.

## 1.19.4
Both server and client are 1.19.4.

It doesn't happen. Can't reproduce it.

----

I'm doing some tests to see what is the cause of the issue.

**Comment by LoneDev6** [comment] 2023-06-06 11:04
Found the issue, will be fixed in the upcoming update

**Closed** 2023-06-06 11:13 UTC
Labels: type: bug
