### ISSUE TITLE
Preview global body should be same as third-persion veiw

### ISSUE THREAD

**Issue by WindUnwaken** [PluginBugs/Issues-CosmeticsCore#172] opened 2023-10-27 14:16 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

wardrobe view is same as blockbenc's cosmetic global view,
but other players looks different.

### Steps to reproduce the issue

1. modify model in blockbench
2. wardobe view will change
3. third-persion view also change
4. you will notice that's different.

### Server version

git-paper-241 1.20.2

### CosmeticsCore Version

Cosmetics 1.2.3

### ProtocolLib Version

5.1.1-SNAPSHOT-669

### LoneLibs Version

1.0.27

### CosmeticsCore config.yml

```shell
cosmetics:
  adventure_backpack_3:
    display_name: "冒險背包3"
    type: BODY_ITEM
    model:
      gui: elitecreatures:adventure_backpack_cosmetic_backpack_3
      normal: elitecreatures:adventure_backpack_cosmetic_backpack_3
      self_2: elitecreatures:adventure_backpack_cosmetic_backpack_3_self
```

### Screenshots/Videos (you can drag and drop files or paste links)

[generated - 複製.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/13189841/generated.-.zip)
[elitecreatures.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/13189858/elitecreatures.zip)

**Comment by LoneDev6** [comment] 2023-11-17 16:32
Duplicate of #173

**Closed by LoneDev6** 2023-11-17 16:32 UTC
Labels: type: duplicate
