### ISSUE TITLE
Erro spam in console

### ISSUE THREAD

**Issue by Gurwi30** [PluginBugs/Issues-CosmeticsCore#111] opened 2023-03-19 20:03 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

𝓖𝓾𝓻𝔀𝓲𝟑𝟎#7746

### What happened?

The plugin is spammin a error coming from sometask in the plugin

### Steps to reproduce the issue

It just gives that error i didn't do anything strange to trigger it

### Server version

1.17.1 Purpur

### CosmeticsCore Version

1.2.0b-r2

### ProtocolLib Version

5.0.0-SNAPSHOT-b616

### LoneLibs Version

1.0.23

### FULL server log

[latest.zip](https://github.com/PluginBugs/Issues-CosmeticsCore/files/11012147/latest.zip)

### Error (optional)

```shell
[19:56:48 WARN]: java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Player.canSee(org.bukkit.entity.Entity)'
[19:56:48 WARN]:        at CosmeticsCore_1.2.0b-r2.jar//dev.lone.cosmeticscore.main.i.c(SourceFile:658)
[19:56:48 WARN]:        at CosmeticsCore_1.2.0b-r2.jar//dev.lone.cosmeticscore.main.j.z(SourceFile:113)
[19:56:48 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:56:48 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[19:56:48 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[19:56:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:56:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:56:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 1
    balloon: 2
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Antares
      x: -229.92081085484884
      y: 68.08334915736522
      z: 176.99429821885965
      yaw: -90.11712
      pitch: 12.483889
  mannequin:
    location:
      world: Antares
      x: -227.39761269586324
      y: 66.0
      z: 177.02919469441926
      yaw: 90.32837
      pitch: -1.6930792
  teleport_area:
    enter:
      world: Antares
      pos1:
        x: -230.0
        y: 69.0
        z: 175.0
      pos2:
        x: -230.0
        y: 66.0
        z: 178.0
    exit_location:
      world: Antares
      x: -231.271283874663
      y: 66.0625
      z: 177.08692632433105
      yaw: 90.0083
      pitch: 0.379542
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
send_creative_hidden_hat_message: true
save:
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

**Comment by LoneDev6** [comment] 2023-03-20 10:40
Duplicate of https://github.com/PluginBugs/Issues-CosmeticsCore/issues/109

**Closed by LoneDev6** 2023-03-20 10:40 UTC
Labels: Bug
