### ISSUE TITLE
Help is not work in paper server

### ISSUE THREAD

**Issue by tjdqls1258** [PluginBugs/Issues-CosmeticsCore#229] opened 2024-05-25 07:50 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

Error occurred while enabling CosmeticsCore v1.2.3d (Is it up to date?) 

### Steps to reproduce the issue

1. use paper-1.19.4-550 ver  sever 
2. ProtocolLib, LoneLibs, CosmeticsCore_1.2.3d in plugins
3. start server
4. Error in server log and not wroking CosmeticsCore plugins

### Server version

This server is running Paper version git-Paper-550 (MC : 1.19.4) 

### CosmeticsCore Version

CosmeticsCore version 1.2.3d

### ProtocolLib Version

ProtocolLib version 5.2.0

### LoneLibs Version

LoneLibs version 1.0.54

### FULL server log

[16:20:12] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:20:13] [ServerMain/INFO]: Loaded 7 recipes
[16:20:14] [Server thread/INFO]: Starting minecraft server version 1.19.4
[16:20:14] [Server thread/INFO]: Loading properties
[16:20:14] [Server thread/INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
[16:20:14] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:20:14] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:20:14] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[16:20:14] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[16:20:14] [Server thread/INFO]: Default game type: SURVIVAL
[16:20:14] [Server thread/INFO]: Generating keypair
[16:20:14] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:20:14] [Server thread/INFO]: Using default channel type
[16:20:14] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[16:20:14] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[16:20:15] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_19_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[16:20:17] [Server thread/WARN]: Legacy plugin ProtocolLibFixer v1.1 does not specify an api-version.
[16:20:17] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[16:20:18] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.54
[16:20:18] [Server thread/INFO]: [ProtocolLibFixer] Loading server plugin ProtocolLibFixer v1.1
[16:20:18] [Server thread/INFO]: [CosmeticsCore] Loading server plugin CosmeticsCore v1.2.3d
[16:20:18] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:20:18] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[16:20:18] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.54
[16:20:18] [Server thread/INFO]: Preparing level "world"
[16:20:18] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:20:18] [Server thread/INFO]: Time elapsed: 86 ms
[16:20:18] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[16:20:18] [Server thread/INFO]: Time elapsed: 22 ms
[16:20:18] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[16:20:18] [Server thread/INFO]: Time elapsed: 16 ms
[16:20:18] [Server thread/INFO]: [ProtocolLibFixer] Enabling ProtocolLibFixer v1.1*
[16:20:18] [Server thread/INFO]: [CosmeticsCore] Enabling CosmeticsCore v1.2.3d
[16:20:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Minecraft: v1_19_R3! Trying to find NMS support
[16:20:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_19_R3' loaded!
[16:20:18] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'LoneLibs' to create a bStats instance!
[16:20:18] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.2.3d (Is it up to date?)
java.lang.NoSuchMethodError: 'void dev.lone.LoneLibs.nbt.nbtapi.NBTItem.saveMetaChanges()'
	at dev.lone.cosmeticscore.main.aC.a(SourceFile:26) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.main.as.a(SourceFile:46) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.main.aq.a(SourceFile:48) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.b.b(SourceFile:109) ~[CosmeticsCore_1.2.3d.jar:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:59) ~[CosmeticsCore_1.2.3d.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[16:20:18] [Server thread/INFO]: [CosmeticsCore] Disabling CosmeticsCore v1.2.3d
[16:20:18] [Server thread/INFO]: Running delayed init tasks
[16:20:18] [Server thread/INFO]: Done (4.466s)! For help, type "help"
[16:20:18] [Server thread/INFO]: Timings Reset

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
  hide_during_combat:
    enabled: true
    combat_duration_ticks: 10000
  fix_invisible_nametag: true
  hide_in_vanish: true
  worlds:
    - "*"
wardrobe_room:
  camera:
    hide_actionbar_texts: true
    use_invisibility_potion: false
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: flat
      x: 205
      y: -58.5
      z: 41
      yaw: 359.85
      pitch: 6.6
  mannequin:
    location:
      world: flat
      x: 204.5
      y: -60
      z: 45.5
      yaw: 180
      pitch: 0
  teleport_area:
    enter:
      world: flat
      pos1:
        x: 167
        y: -61
        z: 42
      pos2:
        x: 167
        y: -57
        z: 37
    exit_location:
      world: flat
      x: 164
      y: -60
      z: 40
      yaw: 98
      pitch: 10
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
send_creative_hidden_hat_message: true
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: "jdbc:mysql://my_url_database_69.com:3306/database_name"
    username: "username"
    password: "password"
    table: "cosmeticscore_saved"
debug: false
```

**Comment by LoneDev6** [comment] 2024-06-05 14:29
Duplicate of https://github.com/PluginBugs/Issues-CosmeticsCore/issues/230

**Closed by LoneDev6** 2024-06-05 14:29 UTC
Labels: type: duplicate
