### ISSUE TITLE
Players are randomly getting kicked for PacketTooLarge

### ISSUE THREAD

**Issue by Mirayii** [PluginBugs/Issues-CosmeticsCore#212] opened 2024-02-28 16:19 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

mirayi

### What happened?

Randomly, players in the same world are getting kicked for PacketTooLarge - PacketPlayOutMount.

I tested this 14 days without CosmeticsCore and everything worked fine. Today, i added it back and the issue started happening again.

### Steps to reproduce the issue

There is no easy reproduction, but i can confirm only few things.
1) This only happens on server with 40+ players and the chances of kicking the players increases with higher player count
2) It can sometimes be achieved by Mounting and Dismounting entities

### Server version

This server is running UniverseSpigot version git-UniverseSpigot-"2ab4558" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 2ab4558 on ver/1.20.4-stable)
Universe-git-UniverseSpigot-"2ab4558" (MC: 1.20.4)

### CosmeticsCore Version

CosmeticsCore version 1.2.3b

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### LoneLibs Version

LoneLibs version 1.0.45

### Error (optional)

```shell
lost connection: Internal Exception: net.minecraft.network.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutMount is 8829902. Max is 8388608
```

### CosmeticsCore config.yml

```shell
lang: en
extract_default_assets: true
cosmetics:
  max_equippable:
    body: 3
    balloon: 2
  hide_during_combat:
    enabled: true
    combat_duration_ticks: 10000
  hide_in_vanish: true
  worlds:
  - '*'
  fix_invisible_nametag: true
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Spawn1
      x: -1309.8471429872698
      y: 73.19984297494273
      z: 416.5420846753168
      yaw: 90.059906
      pitch: 0.37683374
    hide_actionbar_texts: true
  mannequin:
    location:
      world: Spawn1
      x: -1314.493146021122
      y: 72.0625
      z: 416.56716374585807
      yaw: -90.32727
      pitch: -0.23860444
  teleport_area:
    enter:
      world: Spawn1
      pos1:
        x: 16.0
        y: 182.0
        z: 183.0
      pos2:
        x: 13.0
        y: 185.0
        z: 183.0
    exit_location:
      world: Spawn1
      x: 14.45534068921352
      y: 180.0
      z: 178.0722792609892
      yaw: 179.48663
      pitch: 0.96906775
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
      add_item_in_blank_slots:
        # This is useful only for some expert users that need to do some crazy stuff.
        # Do not enable it if you don't know what you are doing.
        enabled: false
        type: PAPER
        custom_model_data: 1337666
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
send_creative_hidden_hat_message: true
```

**Comment by LoneDev6** [comment] 2024-02-28 16:21
Install the new version and let me know.
It probably is a duplicate of this: #209

**Closed by LoneDev6** 2024-02-28 16:21 UTC
Labels: type: bug
