### ISSUE TITLE
[CosmeticsCore] Unhandled exception occurred in onPacketSending(PacketEvent) for CosmeticsCore java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by hed516** [PluginBugs/Issues-CosmeticsCore#270] opened 2024-11-06 10:43 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

????????????????

### Steps to reproduce the issue

[18:33:07 ERROR]: [CosmeticsCore] Unhandled exception occurred in onPacketSending(PacketEvent) for CosmeticsCore
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableList.remove(ImmutableCollections.java:260) ~[?:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar/dev.lone.cosmeticscore.nms.aH.impl.v1_21_1.b(SourceFile:199) ~[[ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar/dev.lone.cosmeticscore.main.y.b(SourceFile:165) ~[[ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar/dev.lone.cosmeticscore.main.y.bm(SourceFile:145) ~[[ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar:?]
        at [ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar/dev.lone.cosmeticscore.main.K.onPacketSending(SourceFile:158) ~[[ia时装]CosmeticsCore_1.3.0-release-2-1730864127524.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[M_ProtocolLib5.30.jar:?]
        at M_ProtocolLib5.30.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[M_ProtocolLib5.30.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:497) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.Connection.send(Connection.java:457) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:313) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:294) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:352) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.entity.CraftPlayer.updateInventory(CraftPlayer.java:1546) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2024) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1586) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[18:33:07 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket@5fecdf95[
    containerId=0
    stateId=176
    items=[0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 1 minecraft:potion, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 1 minecraft:netherite_axe, 1 minecraft:flint_and_steel, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 5 minecraft:spawner, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 16 minecraft:paper, 1 minecraft:paper, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 0 minecraft:air, 1 minecraft:netherite_sword, 1 minecraft:netherite_pickaxe, 0 minecraft:air, 0 minecraft:air, 1 minecraft:pink_bed, 1 minecraft:glow_item_frame, 1 minecraft:player_head, 1 minecraft:enchanted_book, 1 minecraft:clock, 0 minecraft:air]
    carriedItem=0 minecraft:air
  ]

### CosmeticsCore Version

newnewnew

### ProtocolLib Version

newnewnewnewnewnew

### LoneLibs Version

newnewnew

**Comment by LoneDev6** [comment] 2024-11-22 14:16
Duplicate of #262

**Closed by LoneDev6** 2024-11-22 14:16 UTC
Labels: type: bug
