### ISSUE TITLE
Error for incomaptiblity or other error..... ;:(

### ISSUE THREAD

**Issue by dinobossytnew** [PluginBugs/Issues-CosmeticsCore#78] opened 2023-01-09 23:30 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

DinoBoss#6985

### What happened?

According to me when I put these 2 plugins itemsadder is deactivated but lone told me to download again so I did it more than 21 times but neither cosmeticore nor itemsadder want to work together.

### Steps to reproduce the issue

1 put itemsadders in your plugins folder.
2 put cosmeticcore in your plugins folder.

### Server version

[20:17:43] [Server thread/INFO]: Checking version, please wait...
[20:17:45] [Thread-15/INFO]: This server is running Paper version git-Paper-365 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 90750a6)
You are 8 version(s) behind

### CosmeticsCore Version

[20:17:20] [Server thread/INFO]: CosmeticsCore version 1.0.6

### ProtocolLib Version

[20:17:41] [Server thread/INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b608
[20:17:41] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[20:17:41] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[20:17:32] [Server thread/INFO]: LoneLibs version 1.0.22
[20:17:32] [Server thread/INFO]: Collection of libs used by my plugins
[20:17:32] [Server thread/INFO]: Authors: LoneDev and others

### FULL server log

https://mcpaste.io/0d33236c097ec973

### Error (optional)

```shell
[20:16:55] [Server thread/ERROR]: Error occurred while enabling CosmeticsCore v1.0.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at dev.lone.itemsadder.api.ItemsAdder.areItemsLoaded(SourceFile:36) ~[ItemsAdder_3.3.0b-r2.jar:?]
	at dev.lone.cosmeticscore.main.E.f(SourceFile:22) ~[CosmeticsCore_1.0.6.jar:?]
	at dev.lone.cosmeticscore.main.j.b(SourceFile:261) ~[CosmeticsCore_1.0.6.jar:?]
	at dev.lone.cosmeticscore.Main.onEnable(SourceFile:50) ~[CosmeticsCore_1.0.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-365]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-365]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-365]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.Main.getDataFolder()" because the return value of "dev.lone.itemsadder.Main.a()" is null
	at ia.m.I.<clinit>(SourceFile:108) ~[ItemsAdder_3.3.0b-r2.jar:?]
	... 15 more
```

### CosmeticsCore config.yml

```shell
defaul
```

### Screenshots/Videos (you can drag and drop files or paste links)

https://vimeo.com/787745464

**Comment by Lerphie** [comment] 2023-01-10 00:38
I confirm! I've been struggling with this problem for over a month now!!! It's just like yours. The developer does not care about its elimination, I have already written to him about it in the discord. The plugin is updated every few months, I don't know what I paid the money for. I understand that there are bugs, but when you don't even have a plugin running, it's terrible.

**Comment by dinobossytnew** [comment] 2023-01-10 02:22
> ¡Confirmo! ¡He estado luchando con este problema durante más de un mes! Es como el tuyo. Al desarrollador no le importa su eliminación, ya le escribí al respecto en el discord. El complemento se actualiza cada pocos meses, no sé para qué pagué el dinero. Entiendo que hay errores, pero cuando ni siquiera tienes un complemento ejecutándose, es terrible.

Es entendible su ira compañero a mi me pasa igual yo llevo desde la 1.0.3 que no puedo usar el plugin, lone me dijo que solo lo descarge otra vez sin funcionar esto la verdad molesta y luego que diga cuando se le califica con 1 estrella que llamamos la atencion amigo porfavor.

**Comment by LoneDev6** [comment] 2023-01-10 11:35
> The developer does not care about its elimination

I don't know why you think this, I've been trying to reproduce this error for a month without success.
I still am trying to identify why it happens only on a little portion of servers.
I'm still working on it.

**Comment by LoneDev6** [comment] 2023-01-10 11:35
Anyway it's a duplicate of this issue report: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/73

**Closed by LoneDev6** 2023-01-10 11:35 UTC
Labels: Bug
