### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Lerphie** [PluginBugs/Issues-CosmeticsCore#206] opened 2024-02-12 13:36 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

mc_coder

### What happened?

I found a very rare problem with the optimization of your plugin. Once in a while (for example once in 2 hours), your plugin starts to lag for 5-10 minutes.

Sparks:
https://spark.lucko.me/TGg0YjiHm0
https://spark.lucko.me/mYxjsqyLQ8

### Steps to reproduce the issue

*

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"e37fa86" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### CosmeticsCore Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/5af0bb92-c61a-45be-97ff-912ccb218550)

### ProtocolLib Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/81f82581-9e03-44dc-96c9-00fe5d759ad7)

### LoneLibs Version

![image](https://github.com/PluginBugs/Issues-CosmeticsCore/assets/66962762/b0132088-4fa6-4291-af15-c824f6e014bc)

**Comment by LoneDev6** [comment] 2024-02-26 12:33
Duplicate of: https://github.com/PluginBugs/Issues-CosmeticsCore/issues/208

**Closed by LoneDev6** 2024-02-26 12:33 UTC
Labels: type: bug
