### ISSUE TITLE
flying after leaving wardrobe

### ISSUE THREAD

**Issue by MelonCraftDE** [PluginBugs/Issues-CosmeticsCore#12] opened 2022-09-19 11:14 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### Discord tag (optional)

Bornyyy#9630

### What happened?

if i enter the wardrobe and leave it, i'm flying.
the Y coordinates are set to "76.0" so the location is 100% set to the ground.

flying is allowed in certain areas, but i wasnt flying at the moment i entered the wardrobe. but after leaving it.

results in: people are getting a message that flying isnt allowed there, because the wardrobe is in an area were flying isnt allowed for randoms.

### Steps to reproduce the issue

1. turn fly on but dont actually fly!
2. walk into the wardrobe
3. leave it with SHIFT
4. fly away

### Server version

> version
[13:09:31 INFO]: Checking version, please wait...
[13:09:32 INFO]: This server is running Paper version git-Paper-153 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 63cb747)

### CosmeticsCore Version

> version CosmeticsCore
[13:08:57 INFO]: CosmeticsCore version 1.0.0-beta1

### ProtocolLib Version

> version ProtocolLib
[13:09:05 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b598
[13:09:05 INFO]: Provides read/write access to the Minecraft protocol.
[13:09:05 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

> version lonelibs
[13:09:02 INFO]: LoneLibs version 1.0.21
[13:09:02 INFO]: Collection of libs used by my plugins
[13:09:02 INFO]: Authors: LoneDev and others

### CosmeticsCore config.yml

```shell
lang: de
cosmetics:
  max_equippable:
    hat: 2
    body: 2
    balloon: 1
wardrobe_room:
  camera:
    rotation:
      enabled: true
    zoom:
      enabled: true
      min: 2
    fade_effect: true
    location:
      world: Towny
      x: -1037.909964428006
      y: 77.62000000476837
      z: 4318.3978532682795
      yaw: 89.799866
      pitch: 6.1500564
  mannequin:
    location:
      world: Towny
      x: -1044.6981137014982
      y: 76.0
      z: 4318.4844724382965
      yaw: -91.70101
      pitch: 3.7500453
  teleport_area:
    enter:
      world: Towny
      pos1:
        x: -1034.0
        y: 78.0
        z: 4320.0
      pos2:
        x: -1034.0
        y: 76.0
        z: 4324.0
    exit_location:
      world: Towny
      x: -1042.407890943353
      y: 76.0
      z: 4310.120570265795
      yaw: 89.34985
      pitch: 14.400021
  gui:
    cursor_default: fermented_spider_eye:9000001
    cursor_rotate: fermented_spider_eye:9000002
    cursor_pointer: fermented_spider_eye:9000003
    dyeing_pointer: fermented_spider_eye:9100003
    tutorial_gui: fermented_spider_eye:9100004
    tutorial_gui_checked: fermented_spider_eye:9100005
    slots:
      colors:
        not_owned: 195,147,57
        owned: 56,67,100
        wearing: 57,70,195
        wearing_preview: 195,120,57
        max_amount_reached: 111,111,111
save:
  # Use only one at a time
  file:
    enabled: true
  mysql:
    enabled: false
    url: jdbc:mysql://my_url_database_69.com:3306/database_name
    username: username
    password: password
    table: cosmeticscore_saved
debug: false
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://user-images.githubusercontent.com/10966963/191005759-51302a43-469e-4f6d-a8ed-8d38c08b9079.png)

![image](https://user-images.githubusercontent.com/10966963/191006010-865f79f1-ebfd-4450-8190-bf1a1a74e237.png)

**Comment by LoneDev6** [comment] 2022-09-19 11:55
Will be fixed, this applies only to people who have flight permission (admins)

**Comment by MelonCraftDE** [comment] 2022-09-19 16:27
sadly this issue still exist :/ all other things are good now.

**Comment by LoneDev6** [comment] 2022-09-19 21:41
I'll check again, there surely is something else causing that which I didn't think about.

**Comment by LoneDev6** [comment] 2022-09-20 12:33
Strange, this is how it works:
1. you enter the wardrobe portal
2. the plugin saves "is flying" and "can fly" flags of the player before entering the wardrobe
3. you enter the wardrobe
4. you exit the wardrobe
5. the plugin restores the flags back

So it's strange, I don't see any reason why flight should be enabled after leaving the wardrobe.

Can you make a video of the issue?

**Comment by MelonCraftDE** [comment] 2022-09-20 13:24
i will make a video, yes.

maybe i can explain it more:
the problem isnt the fly flag itself, the people have it. and they do have permissions to fly, but not in the wardrobe area. but i'm allowed to fly. so i do fly. other people are getting the message "flying isnt allowed here" because the plugin forces them to fly after leaving the wardrobe. and yea, at this time they do have the fly flag, but they aren't flying.

on my server flying is allowed in certain areas.
but the wardrobe is placed at a area were flying IS NOT allowed.
but after we leave the wardrobe we ARE actually flying.

**Comment by MelonCraftDE** [comment] 2022-09-20 13:33
https://www.youtube.com/watch?v=e8fExX3giDo

Here is a video of the issue.

**Comment by MelonCraftDE** [comment] 2022-09-21 05:52
just realised: if i'm in creative mode, fly is turned off by force, so the character isn't flying. 
if i'm in survival mode, fly remains on and the character starts flying.

**Comment by LoneDev6** [comment] 2022-09-21 09:37
I'll try again but I really can't reproduce the issue, are you sure you don't have any rule or plugin which triggers players fly on teleport?

**Comment by LoneDev6** [comment] 2022-09-21 12:02
In the next update I'll forcefully toggle off flight after teleporting the player back.
This should fix any incompatibilities with other plugins or spawn areas settings.

**Closed** 2022-09-22 16:00 UTC
Labels: Bug
