### ISSUE TITLE
Wardrobe organization

### ISSUE THREAD

**Issue by AidenJules** [PluginBugs/Issues-CosmeticsCore#154] opened 2023-08-29 18:22 UTC
### Terms

- [X] I'm using the very latest version of CosmeticsCore and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CosmeticsCore/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cosmeticscore/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

AidenJules

### Describe the solution you'd like

Hello!
I was talking with ItzASecret in the discord server trying to troubleshoot any way to organize the wardrobe and we couldn't find one. I am trying to organize my cosmetics because I have tons of items and I would like them to have some sort of organization system so that all the hats from pack 1 can go before all the hats from pack 2. Same thing with other types of cosmetics. Maybe if there was a configuration addition that allowed defining the position in the wardrobe GUI, like the first slot is 1, then 2, etc.

### Is your feature request related to a problem?

Yes, but it isn't a big problem? I tried alphabetically and alphanumerically remaining items inside of the config and thought that would fix the order of my items and it did for the first few items but the rest didn't, I got support on it and found out its not a feature and I should request it. The few that got organized appear to be a coincidence.

### Describe alternatives you've considered

I currently just plan to have my wardrobe unorganized for the time being, I have put the name of the pack before the item so there's something defining that but the physical order itself will remain all over for now.

### Additional context

I would really appreciate if this gets considered, I think this could help out tons of servers and it isn't just specific to my case<3

**Comment by LoneDev6** [comment] 2023-09-06 13:48
I'm sure order of cosmetics is based on their namespace+key.
In order to order various packs you can just rename them accordingly.

Code:
```java
        TreeMap<String, AbstractProperties> tmpReordered = new TreeMap<>(REGISTRY);
        REGISTRY.clear();
        REGISTRY.putAll(tmpReordered);
```

From the Java docs:
> TreeMap:
> A Red-Black tree based NavigableMap implementation. The map is sorted according to the natural ordering of its keys

**Comment by LoneDev6** [comment] 2023-11-07 11:36
Duplicate of https://github.com/PluginBugs/Issues-CosmeticsCore/issues/158

**Closed by LoneDev6** 2023-11-07 11:36 UTC
Labels: type: feature request, status: need more info
